apiVersion: v1
kind: ServiceAccount
metadata:
  name: janitor
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: janitor
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "serviceaccounts"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update", "list", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: janitor
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
subjects:
- kind: ServiceAccount
  name: janitor
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
roleRef:
  kind: Role
  name: janitor
  apiGroup: rbac.authorization.k8s.io
