apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
  labels:
    app: runner
  annotations:
    checksum/config: {{(include (print $.Template.BasePath "/runner-configmap.yaml") . | sha256sum) | quote }}
spec:
  replicas: {{ .Values.runner.replicaCount }}
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      serviceAccountName: runner
      imagePullSecrets:
        - name: {{ include "secretname.dockerconfig" . }}
      securityContext:
      {{- include "common.podSecurityContext" . | nindent 8 }}
    {{- if include "adot.isK8sVersionGte129" .}}
      initContainers:
        {{- include "adot.sidecar" (merge (dict "isJob" true) .)  | nindent 8 -}}
    {{- end}}
      containers:
        - name: runner
          image: "{{ include "runner.image.registry" . }}/{{ .Values.runner.image.name }}:{{ .Values.runner.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.runner.image.pullPolicy }}
          securityContext:
            {{- include "common.containerSecurityContext" (dict "readOnlyRootFilesystem" false) | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.runner.service.httpPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.runner.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.runner.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.runner.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: runner
            {{- if and .Values.runner.envFromSecrets (gt (len .Values.runner.envFromSecrets) 0) }}
            {{- range .Values.runner.envFromSecrets }}
            - secretRef:
                name: {{ .ref }}
                {{- if .key }}
                optional: false
                {{- end }}
            {{- end }}
            {{- end }}
          env:
          {{- if and .Values.runner.env (gt (len .Values.runner.env) 0) }}
            {{- toYaml .Values.runner.env | nindent 12 }}
          {{- end }}
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: accesskey
                  key: ACCESS_KEY
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            {{- include "adot.logVolumeMount" (dict "readOnly" false) | nindent 12 }}
        {{- if not (include "adot.isK8sVersionGte129" .) }}
        {{- include "adot.sidecar" . | nindent 8 }}
        {{- end }}
      volumes:
      {{- include "adot.volumes" . | nindent 8 }}
      {{- with .Values.runner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
