apiVersion: v1
kind: Service
metadata:
  name: runner
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | trunc 63 | trimSuffix "-" }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.runner.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: runner
