apiVersion: v2
name: backline
description: Backline on-prem stack
type: application
version: 1.0.1
appVersion: "1.0.0"

dependencies:
  - name: minio
    version: "5.4.0"
    repository: "https://charts.min.io/"
    condition: minio.enabled
